# Generated by Django 3.0.7 on 2020-12-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
        ('railmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmessage',
            name='sniffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sniffer.Sniffer'),
        ),
    ]
