# Generated by Django 3.0.7 on 2020-12-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
        ('railmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmessage',
            name='sniffer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='sniffer.Sniffer'),
        ),
    ]
