# Generated by Django 3.0.6 on 2020-11-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessage',
            name='insert_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
