# Generated by Django 3.0.6 on 2020-11-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0002_rawmessage_insert_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmessage',
            old_name='insert_date',
            new_name='recv_date',
        ),
        migrations.RenameField(
            model_name='rawmessage',
            old_name='insert_time',
            new_name='recv_time',
        ),
    ]
