# Generated by Django 3.0.7 on 2020-12-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
        ('railmessages', '0002_auto_20201225_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmessage',
            name='sniffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sniffer.Sniffer'),
        ),
    ]
