# Generated by Django 3.0.7 on 2020-12-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
        ('railmessages', '0002_auto_20201224_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmessage',
            name='sniffer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sniffer.Sniffer'),
        ),
    ]
