# Generated by Django 3.0.6 on 2020-12-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0003_auto_20201130_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
            ],
        ),
    ]
