# Generated by Django 3.0.6 on 2020-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0004_commandmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['id', 'msg_raw'], name='railmessage_id_4836a3_idx'),
        ),
    ]
