# Generated by Django 3.0.7 on 2020-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0005_auto_20201225_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnplausibleMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='commandmessage',
            name='railmessage_id_e54dcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmessage',
            name='railmessage_id_4836a3_idx',
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='received',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='commandmessage',
            index=models.Index(fields=['address', 'sniffer', 'received'], name='railmessage_address_e1fd16_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['msg_raw'], name='railmessage_msg_raw_5b9f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='unplausiblemessages',
            index=models.Index(fields=['received'], name='railmessage_receive_c68763_idx'),
        ),
    ]
