# Generated by Django 3.0.7 on 2020-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0006_auto_20201227_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandmessage',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='parameters',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='type',
            field=models.CharField(choices=[('def', 'NONE'), ('dcc', 'Digital Command Control'), ('mfx', 'Maerklin MFX')], default='def', max_length=3),
        ),
        migrations.AlterField(
            model_name='commandmessage',
            name='address',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
