# Generated by Django 3.0.7 on 2020-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0007_auto_20201227_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandmessage',
            options={'verbose_name': 'Command Message', 'verbose_name_plural': 'Command Messages'},
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='msg_type',
            field=models.CharField(choices=[('def', 'NONE'), ('dcc', 'Digital Command Control'), ('mfx', 'Maerklin MFX')], default='def', max_length=3),
        ),
    ]
