# Generated by Django 3.0.7 on 2021-01-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0008_auto_20201227_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnplausibleMessages',
        ),
    ]
