# Generated by Django 3.0.7 on 2021-01-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmessages', '0009_delete_unplausiblemessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandmessage',
            name='asset_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commandmessage',
            name='unplausible',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
