# Generated by Django 3.0.7 on 2021-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='verbose_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
