# Generated by Django 3.0.6 on 2020-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniffer',
            name='last_connection',
            field=models.DateField(auto_now=True),
        ),
    ]
