# Generated by Django 3.0.6 on 2020-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_sniffer_last_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
