# Generated by Django 3.0.6 on 2020-09-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20200916_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sniffer',
        ),
    ]
