# Generated by Django 3.0.7 on 2021-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20210108_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='verbose_name',
            field=models.CharField(max_length=512),
        ),
    ]
