# Generated by Django 3.0.7 on 2021-01-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20210108_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='verbose_name',
        ),
    ]
