language: python
python:
  - "3.8"
  - "3.9"      
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
env:
  - SECRET_KEY=123456NOTTHEACTUALKEY ALLOWED_HOSTS=* DEBUG=True
script:
  - python manage.py migrate
  - python manage.py test 
