version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - $PWD/djangodata:/usr/web/app
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    links:
      - influxdb
  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_ADMIN_USER=adminuser
      - INFLUXDB_WRITE_USER=user
      - INFLUXDB_WRITE_USER_PASSWORD=userpassword
      - INFLUX_DB=omrr
    volumes:
      - $PWD/influxdata:/var/lib/influxdb