# Generated by Django 3.0.7 on 2020-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sniffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=17)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connection', models.DateTimeField(null=True)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
