# Generated by Django 3.0.6 on 2020-09-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='mac',
            field=models.CharField(max_length=17),
        ),
    ]
