# Generated by Django 3.0.6 on 2020-09-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0002_auto_20200917_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
