# Generated by Django 3.0.6 on 2020-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0004_auto_20200917_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniffer',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
