# Generated by Django 3.0.6 on 2020-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0005_sniffer_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='last_connection',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
