# Generated by Django 3.0.6 on 2020-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffer', '0006_auto_20201130_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffer',
            name='last_connection',
            field=models.DateTimeField(null=True),
        ),
    ]
